server:
  port: 9300

#spring:
#  h2:
#    console:
#      path: /h2-db
#      url: jdbc:h2:mem:genius

datasource.oracle:
  #driver-class-name : net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  dirver-class-name : oracle.jdbc.driver.OracleDriver
  #url : jdbc:log4jdbc:oracle:thin:@10.49.5.201:1533/LFMD
  url : jdbc:oracle:thin:@10.49.5.201:1533/LFMD
  username : LFMPLS
  password : lfmd1
#  dirver-class-name : com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://1.238.99.203:3306/geniuschung?serverTimezone=Asia/Seoul
#  username: geniuschung
#  password: gege0097

datasource.h3:
  driver-class-name: org.h2.Driver
  #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  url: jdbc:h2:mem:test_h3;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:schema.sql'\;RUNSCRIPT FROM 'classpath:data.sql'
  #url: jdbc:log4jdbc:h2:mem:testt;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:schema.sql'\;RUNSCRIPT FROM 'classpath:data.sql'
  username: geniuschung
  password: gege0097


datasource.h2:
  driver-class-name: org.h2.Driver
  #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:schema.sql'\;RUNSCRIPT FROM 'classpath:data.sql'
  #url: jdbc:log4jdbc:h2:mem:testt;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:schema.sql'\;RUNSCRIPT FROM 'classpath:data.sql'
  username: geniuschung
  password: gege0097

#  datasource:
#    driver-class-name: org.h2.Driver
#    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:h2:mem:test
#    #url: jdbc:log4jdbc:h2:mem:test
#    username: geniuschung
#    password: gege0097

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:mysql://1.238.99.203:3306/geniuschung?serverTimezone=Asia/Seoul
    #url: jdbc:mysql://192.168.35.17:3306/geniuschung?serverTimezone=Asia/Seoul
    #url: jdbc:log4jdbc:h2:mem:test
#    username: geniuschung
#    password: gege0097

spring:
  jpa:
#    #database-platform: org.hibernate.dialect.H2Dialect
#    #database: H2
#    #generate-ddl: false
#    #open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql : true
        use_sql_comments : true

#    #  naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
#    #properties:
#      #hibernate.cache.use_second_level_cache: true
#      #hibernate.cache.use_query_cache: false
#      #hibernate.generate_statistics: true
#      #hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

# 로그 설정 
#TRACE  <  DEBUG  <  INFO  <  WARN  <  ERROR

logging:
  level:
    root: info
    org.hibernate.type.descriptor.sql: trace
    com:
      genius:
        devenv:
          repository: info



