server:
  port: 9300

spring:
  h2:
    console:
      path: /h2-db

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: geniuschung
    password: gege0097
    data: classpath*:data.sql

